openapi: 3.0.3
info:
    title: TODO API
    version: 1.0.0
    description: >
        API de gestion d'une TODO List.
servers:
    -   url: http://localhost:8080
        description: Serveur local de développement

tags:
    -   name: tasks
        description: Opérations sur les tâches

paths:
    /tasks:
        get:
            tags: [ tasks ]
            summary: Récupérer l'ensemble des tâches
            operationId: getTasks
            parameters:
                -   name: todo-only
                    in: query
                    description: Indique s'il faut seulement récupérer les tâches à réaliser
                    required: false
                    schema:
                        type: boolean
            responses:
                '200':
                    description: Liste des tâches récupérée avec succès
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/TaskResponse'
                '204':
                    description: Aucune tâche trouvée
                '500':
                    description: Erreur interne du serveur
        post:
            tags: [ tasks ]
            summary: Créer une tâche
            operationId: createTask
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TaskRequest'
            responses:
                '201':
                    description: Tâche créée avec succès
                    headers:
                        Location:
                            description: URL de la ressource créée
                            schema:
                                type: string
                                example: /tasks/1
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TaskResponse'
                '400':
                    description: Paramètres invalides
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Error'
                '500':
                    description: Erreur interne du serveur

    /tasks/{id}:
        parameters:
            -   in: path
                name: id
                required: true
                description: Identifiant numérique de la tâche
                schema:
                    type: integer
                    minimum: 1
        get:
            tags: [ tasks ]
            summary: Récupérer une tâche
            description: Récupérer une tâche par son identifiant
            operationId: getTaskById
            responses:
                '200':
                    description: Tâche trouvée avec succès
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TaskResponse'
                '404':
                    description: Tâche non trouvée
                '500':
                    description: Erreur interne du serveur
        put:
            tags: [ tasks ]
            summary: Modifier une tâche
            description: Modifie une tâche à partir d'un JSON
            operationId: updateTask
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TaskRequest'
            responses:
                '204':
                    description: Tâche modifiée avec succès
                '400':
                    description: Paramètres invalides
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Error'
                '404':
                    description: Tâche non trouvée
                '500':
                    description: Erreur interne du serveur
        delete:
            tags: [ tasks ]
            summary: Supprimer une tâche
            description: Supprime une tâche par ID
            operationId: deleteTask
            responses:
                '204':
                    description: Tâche supprimée avec succès
                '404':
                    description: Tâche non trouvée
                '500':
                    description: Erreur interne du serveur

components:
    schemas:
        TaskRequest:
            type: object
            description: DTO pour la création ou modification d'une tâche
            properties:
                title:
                    type: string
                    maxLength: 50
                    example: Acheter du lait
                description:
                    type: string
                    maxLength: 255
                    example: 2L demi-écrémé
                done:
                    type: boolean
                    example: false
            required:
                - title
        TaskResponse:
            type: object
            description: Représentation d'une tâche en sortie
            properties:
                id:
                    type: integer
                    example: 1
                title:
                    type: string
                    example: Acheter du lait
                description:
                    type: string
                    example: 2L demi-écrémé
                done:
                    type: boolean
                    example: false
            required:
                - id
                - title
                - done
        Error:
            type: object
            description: DTO d'erreur pour la validation
            properties:
                field:
                    type: string
                    example: title
                description:
                    type: string
                    example: Title is required
